### ISSUE TITLE
When existing miner is connected to an existing aggregator, indicators are not pushed

### ISSUE THREAD

**Issue by jtschichold** [PaloAltoNetworks/minemeld-core#213]
## Description
When an already existing miner is connected to an already existing aggregator, the indicators inside the miner are not pushed to the aggregator.

## How to reproduce

Install the following config and commit:
```
nodes:
  miner_1:
    inputs: []
    output: true
    prototype: spamhaus.DROP
  miner_2:
    inputs: []
    output: true
    prototype: spamhaus.EDROP
  IPv4Aggregator:
    inputs:
      - miner_1
    output: true
    prototype: stdlib.aggregatorIPv4Generic
  IPv4Feed:
    inputs:
      - IPv4Aggregator
    output: false
    prototype: stdlib.feedHCWithValue
```

When the engine is running again, connect IPv4Aggregator to miner_2 and commit again.

**Expected** the number of indicators in IPv4Aggregator should increase and should be roughly the sum of the indicators in miner_1 and miner_2

**Result** number of indicators in IPv4Aggregator does not increment, and there no UPDATEs are produced by miner_2
